# Generated by Django 2.2.5 on 2020-03-10 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_list',
            field=models.ManyToManyField(related_name='my_pending_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FriendShip',
        ),
    ]
