# Generated by Django 2.2.6 on 2020-03-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendShip',
        ),
    ]
