# Generated by Django 2.2.5 on 2020-03-13 16:16

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_member_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='image profile'),
        ),
    ]
