<<<<<<< HEAD
# Generated by Django 2.2.6 on 2020-03-15 19:12
=======
# Generated by Django 2.2.5 on 2020-03-15 19:45
>>>>>>> 0d7e5f3fbb050698ba874e4cb5974d8752a32d47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200313_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_list',
            field=models.ManyToManyField(blank=True, related_name='contacters', to=settings.AUTH_USER_MODEL),
        ),
    ]
