# Generated by Django 2.2.5 on 2020-02-25 17:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='countries',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
