# Generated by Django 2.2.5 on 2020-02-26 15:16

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20200225_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_profile',
            field=models.ImageField(upload_to=userProfile.models.user_directory_path, verbose_name='image profile'),
        ),
    ]
