# Generated by Django 2.2.6 on 2020-02-29 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='forbidden_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
